name: CI - Python Tests and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff black mypy

      - name: Run tests
        run: |
          pytest --tb=short

      - name: Lint with ruff
        run: |
          ruff aws/ tests/ migwelder.py

      - name: Check formatting with black
        run: |
          black --check aws/ tests/ migwelder.py

      - name: Type check with mypy
        run: |
          mypy aws/ migwelder.py
